package net.zentao.quality.api;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import net.zentao.quality.domain.Bug;
import io.swagger.v3.oas.annotations.media.Schema;

/** Bug 视图（quality 卡 §3.1 全字段；字段集合与 contract BugView 一一对应）。 */
public record BugView(
    long id,
    long productId,
    long branchId,
    long categoryId,
    long projectId,
    long executionId,
    Long planId,
    Long storyId,
    Long taskId,
    Long testCaseId,
    Long testRunId,
    String title,
    String keywords,
    int severity,
    int priority,
    @Schema(allowableValues = {"automation", "codeerror", "config", "designdefect", "install", "others",
        "performance", "security", "standard"}) String type,
    String os,
    String browser,
    String steps,
    String openedBuilds,
    @Schema(allowableValues = {"active", "closed", "resolved"}) String status,
    boolean confirmed,
    int activatedCount,
    LocalDate deadline,
    String assignee,
    Instant assignedAt,
    @Schema(allowableValues = {"bydesign", "duplicate", "external", "fixed", "notrepro", "postponed",
        "tostory", "willnotfix"}) String resolution,
    String resolvedBy,
    Instant resolvedAt,
    String resolvedBuild,
    Long duplicateOfId,
    List<Long> relatedBugIds,
    List<String> notifyAccounts,
    String closedBy,
    Instant closedAt,
    Map<String, Object> customFields,
    String createdBy,
    Instant createdAt,
    String updatedBy,
    Instant updatedAt,
    int lockVersion) {

  public static BugView of(Bug bug) {
    return new BugView(
        bug.id(),
        bug.productId(),
        bug.branchId(),
        bug.categoryId(),
        bug.projectId(),
        bug.executionId(),
        bug.planId(),
        bug.storyId(),
        bug.taskId(),
        bug.testCaseId(),
        bug.testRunId(),
        bug.title(),
        bug.keywords(),
        bug.severity(),
        bug.priority(),
        bug.type(),
        bug.os(),
        bug.browser(),
        bug.steps(),
        bug.openedBuilds(),
        bug.status(),
        bug.confirmed(),
        bug.activatedCount(),
        bug.deadline(),
        bug.assignee(),
        bug.assignedAt(),
        bug.resolution(),
        bug.resolvedBy(),
        bug.resolvedAt(),
        bug.resolvedBuild(),
        bug.duplicateOfId(),
        bug.relatedBugIds(),
        bug.notifyAccounts(),
        bug.closedBy(),
        bug.closedAt(),
        bug.customFields(),
        bug.createdBy(),
        bug.createdAt(),
        bug.updatedBy(),
        bug.updatedAt(),
        bug.lockVersion());
  }
}
